### ISSUE TITLE
Enhancements: Tooltips, CSS-Klassen für Container

### ISSUE THREAD

**Issue by johannes-bittner** [georgpreissl/contao-grix-sitebuilder#1]
Großartige Erweiterung - endlich ein Tool, das man ggfs. auch auf Redakteure loslassen könnte! 
Zwei Verbesserungs-/Ergänzungsvorschläge: 

1. Tooltips für alle Bearbeitungs-Icons - gerade am Anfang sicher hilfreich angesichts der Fülle der Möglichkeiten.
2. Möglichkeit, einzelnen Container-Elementen CSS-Klassen vergeben zu können (bspw., um Hintergrundfarben vergeben zu können etc.)

**Comment by georgpreissl** [comment]
Spalten und Reihen können seit dem Release 1.0.4 mit CSS-Klassen ausgezeichnet werden.
Diese CSS-Klassen müssen zuvor im Backend-Modul "Grix CSS" (im Bereich Layout zu finden) definiert werden.
Anschließend stehen sie bei einem Klick auf das Gear-Icon einer Spalte/Reihe zur Auswahl.
